### ISSUE TITLE
Undefined method `source_buffer_for'  for "/code":String

### ISSUE THREAD

**Issue by pbrisbin** [codeclimate/codeclimate#111]
```
jordan$ codeclimate analyze -f text
Starting analysis
Running eslint: Done!

== Brocfile.js (7 issues) ==
error: (NoMethodError) undefined method `source_buffer_for' for "/code":String
This is especially confusing because there is no method (or even text string) source_buffer_for anywhere in my project, which leads me to believe this error is coming from codeclimate.
```

/cc @elwayman02

**Comment by elwayman02** [comment]
Please let me know what information you need, though most of it is in #82 already.

**Comment by pbrisbin** [comment]
Thanks, will definitely let you know. To centralize some debugging info:

**.codeclimate.yml**:

```yaml
---
engines:
  eslint:
    enabled: true
  csslint:
    enabled: false
  fixme:
    enabled: true
  watson:
    enabled: true
ratings:
  paths:
  - "app/**"
exclude_paths:
- bower_components/**/*
- dist/**/*
- node_modules/**/*
- tests/**/*
- tmp/**/*
- vendor/**/*
```

Ember 1.12 app w/ over 32,000 lines of code across 200+ files.

Please let me know if any of this is out of date.
