### ISSUE TITLE
"codeclimate init && codeclimate validate-config" generates an unexpected key

### ISSUE THREAD

**Issue by kevinburkeshyp** [codeclimate/codeclimate#13]
"codeclimate init" on a JS-heavy project generated

```yml
---
engines:
  coffeelint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
  paths:
  - "**.coffee"
  - "**.js"
  - "**.jsx"
  - "**.css"
```

I then ran `codeclimate validate-config` and was told:

```
WARNING: unexpected key "ratings", dropping
```

I am running version 0.0.1.
