### ISSUE TITLE
CC::Analyzer::UnreadableFileError on a path that should be excluded

### ISSUE THREAD

**Issue by pnomolos** [codeclimate/codeclimate#215]
```yaml
engines:
  rubocop:
    enabled: true
  bundler-audit:
    enabled: true
ratings:
  paths:
  - "lib/**/*"
  - Gemfile
exclude_paths:
 - "test/**/*"
 - ".pry_history"
```

Running `codeclimate analyze` produces the following:

```
fatal: bad config file line 31 in .git/config
error: (CC::Analyzer::UnreadableFileError) Can't read ./.pry_history
```

(I'm also not sure what's up with the "fatal" error regarding '.git/config' as all seems normal there)
