### ISSUE TITLE
Be able to change rules of engine either on site or in config 

### ISSUE THREAD

**Issue by mgracer48** [codeclimate/codeclimate#231]
For example some devs might not like some rules by pep 8 like max line and might want to disable that rule

**Comment by GordonDiggs** [comment]
@mgracer48 This is supported! You can either exclude checks inside the `.codeclimate.yml` file, or if the library supports a configuration file, you can tweak the settings there.

Example yaml snippet:

```yaml
engines:
  pep8:
    enabled: true
    checks:
      W293:
        enabled: false
```

pep8 configuration: http://pep8.readthedocs.org/en/latest/intro.html#configuration
