### ISSUE TITLE
Syntax error when running brakeman engine

### ISSUE THREAD

**Issue by floriank** [codeclimate/codeclimate#233]
I am currently investigating an issue where the `brakeman` engine fails consistently for one of my private repos.

Trying this locally with `codeclimate-cli` via running:

```
docker run   --interactive --tty --rm   --env CODE_PATH="$PWD"   --volume "$PWD":/code   --volume /var/run/docker.sock:/var/run/docker.sock   --volume /tmp/cc:/tmp/cc --env CODECLIMATE_DEBUG=1  codeclimate/codeclimate analyze
```

will run into:

```bash
Running brakeman: Done!
error: (CC::Analyzer::Engine::EngineFailure) engine brakeman failed with status 2 and stderr 
sh: 1: Syntax error: "(" unexpected
backtrace: /usr/src/app/lib/cc/analyzer/raising_container_listener.rb:23:in `finished'
        /usr/src/app/lib/cc/analyzer/composite_container_listener.rb:17:in `block in finished'
        /usr/src/app/lib/cc/analyzer/composite_container_listener.rb:17:in `each'
        /usr/src/app/lib/cc/analyzer/composite_container_listener.rb:17:in `finished'
        /usr/src/app/lib/cc/analyzer/container.rb:65:in `run'
        /usr/src/app/lib/cc/analyzer/engine.rb:42:in `run'
        /usr/src/app/lib/cc/analyzer/engines_runner.rb:60:in `block in run_engine'
        /usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:74:in `with_spinner'
        /usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:55:in `block in engine_running'
        /usr/src/app/lib/cc/analyzer/formatters/formatter.rb:18:in `engine_running'
        /usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:54:in `engine_running'
        /usr/src/app/lib/cc/analyzer/engines_runner.rb:59:in `run_engine'
        /usr/src/app/lib/cc/analyzer/engines_runner.rb:23:in `block in run'
        /usr/src/app/lib/cc/analyzer/engines_runner.rb:23:in `each'
        /usr/src/app/lib/cc/analyzer/engines_runner.rb:23:in `run'
        /usr/src/app/lib/cc/cli/analyze.rb:20:in `block in run'
        /usr/src/app/lib/cc/cli/analyze.rb:18:in `chdir'
        /usr/src/app/lib/cc/cli/analyze.rb:18:in `run'
        /usr/src/app/lib/cc/cli/command.rb:24:in `execute'
        /usr/src/app/lib/cc/cli/runner.rb:27:in `run'
        /usr/src/app/lib/cc/cli/runner.rb:9:in `run'
        /usr/src/app/bin/codeclimate:9:in `<main>'
```

The `.codeclimate.yml` looks like this:

```yaml
---
engines:
  brakeman:
    enabled: yes
  bundler-audit:
    enabled: no
  csslint:
    enabled: no
  coffeelint:
    enabled: no
  eslint:
    enabled: no
  fixme:
    enabled: no
  rubocop:
    enabled: no
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.rb"
  - "**.css"
  - "**.scss"
  - "**.coffee"
  - "**.js"
  - "**.jsx"
exclude_paths:
- config/**/*
- db/**/*
- script/**/*
- spec/**/*
- vendor/**/*
- public/**/*
```
to only include the `brakeman` engine. 

I am currently using the `codeclimate-brakeman` docker image in the `latest` version (`ac129987bac1`).

As the github.com/codeclimate/codeclimate-brakeman repo seems to be gone, I can really look into this. 

Any hints  or tips?
