### ISSUE TITLE
codeclimate validate-config:  unexpected key "languages", dropping

### ISSUE THREAD

**Issue by klippx** [codeclimate/codeclimate#24]
According to how to set up .codeclimate.yml we should add a key `languages` to the yml file, source: http://docs.codeclimate.com/article/289-configuring-your-repository-via-codeclimate-yml

However, running validate-config against this gives an error:

```
> codeclimate validate-config
WARNING: unexpected key "languages", dropping
```

```
> codeclimate version
0.0.6
```

That doesn't make sense...

My .codeclimate.yml is a mix of what `codeclimate init` gives and what the instructions on the given web page says:

```
---
#
# ---Choose Your Languages---
# To disable analysis for a certain language, set the language to `false`.
# For help setting your languages:
# http://docs.codeclimate.com/article/169-configuring-analysis-languages
#
languages:
   Ruby: true
   JavaScript: false
   Python: false
   PHP: false
engines:
  rubocop:
    enabled: true
  coffeelint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
  paths:
  - "**.rb"
  - "**.coffee"
  - "**.js"
  - "**.jsx"
  - "**.css"
exclude_paths:
- config/**/*
- db/**/*
- spec/**/*
- vendor/**/*
```
