### ISSUE TITLE
Engine timeout :(

### ISSUE THREAD

**Issue by eproulx-petalmd** [codeclimate/codeclimate#270]
Hi,

Brakeman engine's always run out of time when analyzing, but when running by itself, it takes about 2 minutes to get the entire results

Running codeclimate analyze:
```
Starting analysis
Running brakeman: Done!
error: (CC::Analyzer::Engine::EngineTimeout) engine brakeman ran for 900000 seconds and was killed
```
Here's my .codeclimate.yml
```
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
ratings:
   paths:
   - app/**
   - lib/**
   - "**.rb"
exclude_paths:
- app/chewy/*
- coverage/**/*
- log/**/*
- public/**/*
- bin/**/*
- api_doc/**/*
- doc/**/*
- tmp/**/*
- spec/**/*
- vendor/**/*

```
