### ISSUE TITLE
Can't configure a custom path for codeclimate-brakeman engine

### ISSUE THREAD

**Issue by wpolicarpo** [codeclimate/codeclimate#275]
I have a custom directory structure and source files are not in the same directory where `.codeclimate.yml` is.

Should be possible to configure a custom path, so `codeclimate-brakeman` can pass it to `brakeman`.

When I run `codeclimate-brakeman` engine, I get this error:

```
Running brakeman: Done!
error: (CC::Analyzer::Engine::EngineFailure) engine brakeman failed with status 1 and stderr
Please supply the path to a Rails application.
```

**Comment by wpolicarpo** [comment]
The configuration could be made in brakeman config section:

```yaml
engines:
  brakeman:
    enabled: true
    config:
      path: path/to/rails/application
```
