### ISSUE TITLE
ratings.paths should take precedence over exclude_paths.

### ISSUE THREAD

**Issue by envygeeks** [codeclimate/codeclimate#294]
The way CodeClimate handles includes and excludes makes for a large and inefficiently managed .codeclimate/.rubocop file.  It would be nice if I could just do:

```yml
ratings:
  paths:
  - lib/**.rb
exclude_paths:
- **/*
```

And it work.
