### ISSUE TITLE
Per-engine exclude_paths options

### ISSUE THREAD

**Issue by KevinBongart** [codeclimate/codeclimate#297]
(originally posted here: https://github.com/codeclimate/codeclimate-duplication/issues/74#issuecomment-171466949, now moving the issue to the correct repo)

Hi, is there a way to configure the engine to ignore some paths? There is a global Code Climate setting:

```yml
---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  rubocop:
    enabled: true
exclude_paths:
- spec/*
```

But I still want other engines to analyze that spec directory, so I tried both:

```yml
---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      exclude_paths:
      - spec/*
  rubocop:
    enabled: true
```

and:

```yml
---
engines:
  duplication:
    enabled: true
    exclude_paths:
    - spec/*
    config:
      languages:
      - ruby
  rubocop:
    enabled: true
```

…but no success. Let me know if I'm doing something wrong, or if this is a future feature!
