### ISSUE TITLE
Excluding paths weird behavior

### ISSUE THREAD

**Issue by jhmilan** [codeclimate/codeclimate#32]
It looks like for any reason my exclude_paths are being ignored.

### setup
This is my local setup

* Mac OS X 10.10.3 (Yosemite)
* boot2docker 1.7.0
* codeclimate CLI 0.0.8 (installed the brew package)
* bash 4.3 (this is not important it worked exactly the same with 3.2 but I had to upgrade it by other reasons)

### codeclimate config

This is my .codeclimate.yml file

```
---
engines:
  phpcodesniffer:
    enabled: false
  coffeelint:
    enabled: true
  eslint:
    enabled: false
  csslint:
    enabled: false
ratings:
  paths:
  - "**.php"
  - "**.js"
  - "**.css"
exclude_paths:
- "node_modules/**/*"
- "vendor/**/*"
- "etc/**/*"
- ".vagrant/**/*"
```

I'm enabling just the coffeelint engine to reproduce it faster. Anyway, the exclude_paths should work no matter the engines, I suppose. Okay, I run `composer analyze` and this is the result:

```
codeclimate analyze
Starting analysis
Running coffeelint: Done!

== node_modules/gulp/node_modules/vinyl-fs/test/fixtures/test.coffee (1 issue) ==
1-1: [stdin]:1:12: error: unexpected !
Hello world!
           ^ [coffeelint]

Analysis complete! Found 1 issue.
```

That's odd. What am I missing here? Why the engine is parsing something within the node_modules folder?

Thanks

=== edited ===

I found a similar issue here https://github.com/codeclimate/codeclimate-csslint/issues/1 I wonder if it is related or even the same stuff.

**Comment by jonathancadepowers** [comment]
@jhmilan Hey! Thanks for the report, and sorry for the trouble.

We just released a new version of the CLI today (version 0.0.9). Go ahead and try updating and then running a new analysis.

To update: `brew update && brew upgrade codeclimate`.

**Comment by jhmilan** [comment]
Paths excluded. Nice!

**Comment by stickel** [comment]
I've updated to the latest version of `codeclimate` and the engines. `codeclimate` is still analyzing directories that are supposed to be excluded.
```shell
---
engines:
  coffeelint:
    enabled: false
  eslint:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.scss"
exclude_paths:
- "node_modules/**/*"
- "app/assets/build/*"
- "app/assets/fonts/*"
- "app/assets/images/*"
- "server/*"
```
And the output still has errors like this:
```shell
== node_modules/webpack/node_modules/webpack-core/node_modules/source-map/node_modules/amdefine/intercept.js (1 issue) ==
0:0-0:0: Cannot find module 'babel-eslint' [eslint]

== server/config/config.js (1 issue) ==
0:0-0:0: Cannot find module 'babel-eslint' [eslint]
```
It's my understanding that even if those errors are legit, they shouldn't be appearing because `codeclimate` should be excluding the `server/**/*` and `node_modules` directories.

**Comment by GordonDiggs** [comment]
@stickel your `server/*` glob is malformed. Each of those should be `**/*` (like the one for `node_modules`). Does it work if you update the config to be:

```yaml
---
engines:
  coffeelint:
    enabled: false
  eslint:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.scss"
exclude_paths:
- "node_modules/**/*"
- "app/assets/build/**/*"
- "app/assets/fonts/**/*"
- "app/assets/images/**/*"
- "server/**/*"
```

**Comment by stickel** [comment]
@GordonDiggs Sorry, poor copy/paste job. My server glob is `server/**/*` in the file. There are no subdirectories in each of `app/assets/[build/fonts/images]`.

**Comment by MattWalker** [comment]
Having the same issue.

- OS X 10.10.3
- boot2docker 1.7.1
- codeclimate CLI 0.1.5

I stripped down `.codeclimate.yml` to:

```yaml
---
engines:
  coffeelint:
    enabled: true
ratings:
  paths:
  - "**.coffee"
exclude_paths:
- "node_modules/**/*"
```

Here's a sample of `codeclimate analyze` output:

```bash
== node_modules/protractor/node_modules/selenium-webdriver/node_modules/xml2js/83.coffee (1 issue) ==
4-4: Line exceeds maximum allowed length [coffeelint]

== node_modules/protractor/node_modules/selenium-webdriver/node_modules/xml2js/incompat.coffee (2 issues) ==
2-2: Line exceeds maximum allowed length [coffeelint]
4-4: Line contains inconsistent indentation [coffeelint]
```

Everything in `node_modules` was processed.
