### ISSUE TITLE
How can I set custom eslintrc file?

### ISSUE THREAD

**Issue by marocchino** [codeclimate/codeclimate#350]
I want to use son config `.eslintrc.json` for code climate.
Is there any way to target it?

I checked https://github.com/codeclimate/codeclimate/blob/master/config/engines.yml but not was there.

**Comment by wfleming** [comment]
Hi @marocchino,

The engine should be using the same config file [ESLint](http://eslint.org/docs/user-guide/configuring#configuration-file-formats) would. If you have a `.eslintrc.json` checked in to the root of your project, it should get used, as long as there's no higher-precedence file present, like `.eslintrc.yml`, etc.

Have you tried using the config file this way and aren't seeing it be used? If so, please provide as many details as you can: what version of the Code Climate CLI you're using, what the contents of your `.eslintrc.json` are, and anything else you can think of.

**Comment by marocchino** [comment]
OK,
This is my settings:

- .codeclimate.yml

  ```yml
  ---
  engines:
    brakeman:
      enabled: true
    bundler-audit:
      enabled: true
    csslint:
      enabled: true
    coffeelint:
      enabled: true
    duplication:
      enabled: true
      config:
        languages:
        - ruby
        - javascript
        - python
        - php
    eslint:
      enabled: true
    fixme:
      enabled: true
    rubocop:
      enabled: true
  ratings:
    paths:
    - Gemfile.lock
    - "**.erb"
    - "**.haml"
    - "**.rb"
    - "**.rhtml"
    - "**.slim"
    - "**.css"
    - "**.coffee"
    - "**.inc"
    - "**.js"
    - "**.jsx"
    - "**.module"
    - "**.php"
    - "**.py"
  exclude_paths:
  - config/**/*
  - db/**/*
  - spec/**/*
  - vendor/**/*
  ```
- .eslint.json

  ```json
  {
      "parser": "babel-eslint",
      "rules": {
          "indent": [
              2,
              2
          ],
          "quotes": [
              2,
              "double"
          ],
          "linebreak-style": [
              2,
              "unix"
          ],
          "semi": [
              2,
              "never"
          ],
          "no-var" : 2,
          "no-unused-vars": 1,
          "no-undef" : 1,
          "prefer-arrow-callback": 2,
          "prefer-const": 1
      },
      "env": {
          "es6": true,
          "browser": true
      },
      "extends": "eslint:recommended"
  }
  ```

and there's no higher-precedence file present.

```
-rw-r--r--@  1 marocchino  staff   8196 Jan 14 15:08 .DS_Store
drwxr-xr-x   3 marocchino  staff    102 Jan 13 16:28 .bundle
-rw-r--r--   1 marocchino  staff    530 Dec 24 10:07 .codeclimate.yml
-rw-r--r--   1 marocchino  staff     87 Nov 27 14:05 .editorconfig
-rw-r--r--@  1 marocchino  staff    140 Feb  5 15:52 .env
-rw-r--r--   1 marocchino  staff    621 Feb 17 10:06 .eslintrc.json
drwxr-xr-x  15 marocchino  staff    510 Feb 16 15:57 .git
-rw-r--r--   1 marocchino  staff    645 Dec 10 10:16 .gitignore
-rw-r--r--   1 marocchino  staff    153 Feb 16 15:48 .hound.yml
-rw-r--r--   1 marocchino  staff   7954 Jan 19 14:12 .rubocop.yml
-rw-r--r--   1 marocchino  staff      6 Jan 13 16:24 .ruby-version
-rw-r--r--   1 marocchino  staff   4615 Jan 21 18:33 .scss-lint.yml
-rw-r--r--   1 marocchino  staff   3112 Feb  5 16:18 Gemfile
-rw-r--r--   1 marocchino  staff  15638 Feb 16 15:03 Gemfile.lock
.. so on ..
```

and 'no-unused-vars' are still reported.
![screen shot 2016-02-17 at 10 13 21 am](https://cloud.githubusercontent.com/assets/128431/13096787/26bb2708-d55f-11e5-8b2f-88ebb6ecec58.png)
