### ISSUE TITLE
Engine-specific wildcard and multi-level exclude_paths are globally applied.

### ISSUE THREAD

**Issue by DavidEBest** [codeclimate/codeclimate#397]
I'm trying to disable just the `duplication` engine for all nested `test` directories in a project, but it appears that wildcard exclusions and multi-level paths get applied to all engines.

This yaml produces (for example) 16 warnings.
``` yaml
engines:
  duplication:
    enabled: true
    exclude_paths:
    - tasks/
    config:
      languages:
      - ruby
  reek:
    enabled: true
ratings:
  paths:
  - "**.rb"
exclude_paths:
- "**/node_modules/**"
- tmp/
```

If I replace `tasks/` with `"**/test/**"` or `tasks/filter-team-data/test`, I receive 15 warnings. The additional warning that is filtered is a reek warning on `tasks/filter-team-data/test/test_team_data_filterer.rb`.

I'm surprised to see a reek warning change based on a modification to `duplication`'s `exclude_paths`. Am I doing something wrong?

I am running `version 0.24.0` on https://github.com/18F/concourse-compliance-testing.
