### ISSUE TITLE
phpmd - specifying rulesets?

### ISSUE THREAD

**Issue by matchdav** [codeclimate/codeclimate#460]
It's not clear in the docs or the output of `codeclimate help` how to use custom `ruleset.xml` files with `phpmd`

halp!

**Comment by pbrisbin** [comment]
Hi @matchdav,

The [sample config section](https://github.com/codeclimate/codeclimate-phpmd#sample-config) includes the following snippet for your `codeclimate.yml`:

```
engines:
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "unusedcode,codesize,naming,optional_relative_path_to_custom_ruleset.xml"
```

Notice `optional_relative_path_to_custom_ruleset.xml`. As long as your `ruleset.xml` file is present in the repository, you can add its path (relative to the repository root) as a value in the `rulesets` key. Unfortunately, we only have access to the repository sources during analysis, so if you keep your ruleset file elsewhere, that won't work at this time.

Hope this helps.

Note: if you have further trouble with this or other engines, please open those issues on the engines' repo directly (e.g. [codeclimate/codeclimate-phpmd](https://github.com/codeclimate/codeclimate-phpmd))
