### ISSUE TITLE
What is proper syntax of exclude_paths?

### ISSUE THREAD

**Issue by remik** [codeclimate/codeclimate#466]
I tried few versions of exclude_paths but it is still not excluding.

My command:
```
[DEBUG] docker run: ["docker", "run", "--name", "cc-engines-fixme-stable-12988981-7e87-4676-82d5-059c5412e541", "--cap-drop", "all", "--label", "com.codeclimate.label=a1a27ef8-ac7f-4a74-b184-2f41e6aba20a", "--memory", "512000000", "--memory-swap", "-1", "--net", "none", "--rm", "--volume", "/mnt1/home/jenkins/workspace/web-codeclimate:/code:ro", "--volume", "/tmp/cc/e8a1336d-40f4-41d3-82e4-c872ae0dd802:/config.json:ro", "--user", "9000:9000", "codeclimate/codeclimate-fixme"]
```

My config:
```
---
engines:
  duplication:
    enabled: false
    config:
      languages:
      - javascript
      - python
  eslint:
    enabled: false
  fixme:
    enabled: true
  radon:
    enabled: true
exclude_paths:
- "static/vendor/**/*"
- "scripts/chatscript/**/*"
- "node_modules/**/*"
```

Example:
```
[DEBUG] fixme:stable engine output: {"categories":["Bug Risk"],"check_name":"TODO","description":"TODO found","location":{"lines":{"begin":170,"end":170},"path":"./node_modules/karma-jasmine/lib/adapter.js"},"type":"issue"}
```
