### ISSUE TITLE
exclude_paths including some excluded files and excluding it's own engines

### ISSUE THREAD

**Issue by Aeolun** [codeclimate/codeclimate#476]
Hi,

I've found some odd behaviour in exclude_paths, which initially made me think it wasn't working.

I'm using the wrapper script.
I've updated the engines to the latest version.

I'm running: `sudo CODECLIMATE_DEBUG=1 codeclimate analyze`

With a config of:

```
---
engines:
  csslint:
    enabled: false
  duplication:
    enabled: false
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: false
  fixme:
    enabled: false
  phpcodesniffer:
    enabled: true
  phan:
    enabled: false
    config:
      file_extensions: "php"
  phpmd:
    enabled: false
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- module/**/*
- config/**/*
- node_modules/**/*
- vendor/**/*
- public/chat/**/*
- **/bin/
```

**Relevant output:**

```
No enabled engines. Add some to your .codeclimate.yml file!
```

After removing `- **/bin/`

```
== vendor/zendframework/zendframework/bin/classmap_generator.php (2 issues) ==
51: Line exceeds 120 characters; contains 123 characters [phpcodesniffer]
159: Line exceeds 120 characters; contains 139 characters [phpcodesniffer]

== vendor/zendframework/zendframework/bin/pluginmap_generator.php (1 issue) ==
64: Line exceeds 120 characters; contains 125 characters [phpcodesniffer]

== vendor/zendframework/zendframework/bin/templatemap_generator.php (2 issues) ==
190: Line exceeds 120 characters; contains 139 characters [phpcodesniffer]
195: Line exceeds 120 characters; contains 173 characters [phpcodesniffer]
```

**Two things I found:**
- Excluding `- **/bin/` is a bad idea, as the system suddenly complains about a lack of engines.
- Even though `- vendor/**/*` is excluded, the system manages to include errors from three files that are excluded. Most of the contents are correctly excluded though. I think this has something to do with engines including files even though excluded (and the output system not checking if I'm interested in them?).

I'm running docker on a Ubuntu VM using Vagrant (Docker version 1.11.2, build b9f10c9).

```
$ uname -a
Linux nature-index 3.13.0-77-generic #121-Ubuntu SMP Wed Jan 20 10:50:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$   docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64
  Include the output of the following commands:
```
