### ISSUE TITLE
Include rubocop-rspec in default rubocop config?

### ISSUE THREAD

**Issue by andyw8** [codeclimate/codeclimate#539]
The RuboCop engine includes the rubocop-rspec gem, but it is disabled by default. Do the Code Climate team have any thoughts on enabling this, along with some of its rules?

**Comment by GordonDiggs** [comment]
@andyw8 Our default configuration aims to be fairly objective and not opinionated. For example, it doesn't enable any style rules by default. I think enabling this gem by default would go against that. WDYT?

**Comment by andyw8** [comment]
Hi @GordonDiggs 

Look at the [defaults](https://github.com/backus/rubocop-rspec/blob/master/config/default.yml), there's some that should be non-controversial:

```
RSpec/EmptyExampleGroup:
  Description: Checks if an example group does not include any tests.
RSpec/Focus:
  Description: Checks if examples are focused.
RSpec/LetSetup:
  Description: Checks unreferenced `let!` calls being used for test setup.
```

But that's probably not enough to justify enabling the gem. Thanks anyway!

cc @bquorning @backus
