### ISSUE TITLE
engine watson failed - no such file or directory, scandir './tests'

### ISSUE THREAD

**Issue by NullVoxPopuli** [codeclimate/codeclimate#575]
Hi there!

Sorry you're having trouble with our CLI, and thanks for taking the time to
report the issue to us.

There are a few reasons _not_ to open an issue here. Please consider the
following:

- Is this an issue with codeclimate.com?

nope -- just using the cli

- Is this an issue with a specific engine?

 ember-watson (engine: watson)

- Is this an issue with your Docker installation in general?

My docker install is swell

- Are you invoking `docker run codeclimate/codeclimate` without other options?

  i'm running `analyze`

- Are you having trouble using this project as a gem or not via Docker?

  While this project is currently available as a gem, that is not a supported
  use-case. It is more an accident of history due to the way our own
  infrastructure is currently designed. Once we address this, we will stop
  releasing this project as a gem.

  We may accept Pull Requests that fix issues with using the project as a gem
  (e.g. correcting version bounds), but we will not ourselves address any Issues
  in this area.

## Guidelines

If you'd still like to report this issue, please follow these guidelines:

- Make sure your problem exists in the latest version of the CLI and any engines
  you're using, the following commands will update everything:

  ```
  docker pull codeclimate/codeclimate
  codeclimate engines:install
  ```

I ran:
```
docko -f docker-compose.test.ci.yml run --rm codeclimate engines:install
```

my compose config is:
```
test-server:
  build: .
  dockerfile: ./Dockerfile
  command: npm run ci
  volumes:
    - .:/web

# currently not working :-(
codeclimate:
  image: codeclimate/codeclimate
  command: analyze /web -f html
  volumes:
    - .:/web

    # codeclimate/codeclimate paths
    - .:/code
    - /var/run/docker.sock:/var/run/docker.sock
    - /tmp/cc:/tmp/cc

    # scss lint paths
    - .:/app

  environment:
    - CODECLIMATE_CODE=/web
    - CODECLIMATE_DEBUG=1

```

- Include the exact command you're running and its complete output

  Please enable debug for these invocations:

  ```
  CODECLIMATE_DEBUG=1 codeclimate analyze
  ```

  If this output is large, consider using a service like gist.github.com.

```
 $ docko -f docker-compose.test.ci.yml run --rm codeclimate
[DEBUG] Couldn't include because part of path doesn't exist. path="./web"
[DEBUG] watson:stable engine config: {"enabled":true,"include_paths":["./"]}
[DEBUG] docker run: ["docker", "run", "--name", "cc-engines-watson-stable-4c99999d-d68f-4b8d-8f1a-ddf861606163", "--cap-drop", "all", "--label", "com.codeclimate.label=08fd427d-911b-4334-97ef-7bf7c03f3cf3", "--memory", "512000000", "--memory-swap", "-1", "--net", "none", "--rm", "--volume", "/web:/code:ro", "--volume", "/tmp/cc/6638b7a8-65a8-4321-ba14-c4f2b78d07d3:/config.json:ro", "--user", "9000:9000", "codeclimate/codeclimate-watson"]
error: (CC::Analyzer::Engine::EngineFailure) engine watson:stable failed with status 1 and stderr 
fs.js:951
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir './tests/'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at walkSync (/usr/lib/node_modules/ember-watson/node_modules/walk-sync/index.js:14:20)
    at module.exports (/usr/lib/node_modules/ember-watson/lib/helpers/find-files.js:11:21)
    at EmberWatson.transformQUnitTest (/usr/lib/node_modules/ember-watson/lib/watson.js:39:16)
    at Command.<anonymous> (/usr/lib/node_modules/ember-watson/bin/ember-watson:55:12)
    at Command.listener (/usr/lib/node_modules/ember-watson/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/usr/lib/node_modules/ember-watson/node_modules/commander/index.js:615:12)
[DEBUG] backtrace: /usr/src/app/lib/cc/analyzer/raising_container_listener.rb:23:in `finished'
	/usr/src/app/lib/cc/analyzer/composite_container_listener.rb:17:in `block in finished'
	/usr/src/app/lib/cc/analyzer/composite_container_listener.rb:17:in `each'
	/usr/src/app/lib/cc/analyzer/composite_container_listener.rb:17:in `finished'
	/usr/src/app/lib/cc/analyzer/container.rb:78:in `run'
	/usr/src/app/lib/cc/analyzer/engine.rb:52:in `run'
	/usr/src/app/lib/cc/analyzer/engines_runner.rb:60:in `block in run_engine'
	/usr/src/app/lib/cc/analyzer/formatters/formatter.rb:29:in `engine_running'
	/usr/src/app/lib/cc/analyzer/engines_runner.rb:59:in `run_engine'
	/usr/src/app/lib/cc/analyzer/engines_runner.rb:23:in `block in run'
	/usr/src/app/lib/cc/analyzer/engines_runner.rb:23:in `each'
	/usr/src/app/lib/cc/analyzer/engines_runner.rb:23:in `run'
	/usr/src/app/lib/cc/cli/analyze.rb:31:in `block in run'
	/usr/src/app/lib/cc/cli/analyze.rb:29:in `chdir'
	/usr/src/app/lib/cc/cli/analyze.rb:29:in `run'
	/usr/src/app/lib/cc/cli/command.rb:70:in `execute'
	/usr/src/app/lib/cc/cli/runner.rb:22:in `run'
	/usr/src/app/lib/cc/cli/runner.rb:8:in `run'
	/usr/src/app/bin/codeclimate:6:in `<main>'
```

- Indicate what you expected to happen and what happened instead - no error?
- Include your operating system, how you run Docker (e.g. Docker Machine) and
  the version of Docker you're using.

  Include the output of the following commands:

  ```
$ uname -a
Linux macbuntu 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false

  env | grep "^DOCKER_"
 # no output

$ docker-compose -v
docker-compose version 1.8.0-rc1, build 9bf6bc6
  ```

- If your project is open source, please provide a URL to the source
- If your project is closed source, but you'd be willing to share a copy with us
  (for example, by emailing an archive), please say so
  - I need to talk to the owner about open sourcing the ember project. No reason frontend code shouldn't be open sourced, imo

**Comment by NullVoxPopuli** [comment]
.codeclimate.yml:
```yml
---
engines:
  scss-lint:
    enabled: false
  watson:
    enabled: true

  duplication:
    enabled: true
    config:
      languages:
        - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
    - "**.scss"
    - "**.js"
    - "**.jsx"
exclude_paths:
  - config/
  - dist/
  - node_modules/
  - tests/
  - vendor/
  - public/
  - coverage/
  - bower_components/
```

**Comment by ABaldwinHunter** [comment]
Hi @NullVoxPopuli! Thanks for writing in. It looks like your code isn't getting mounted into the codeclimate container correctly:

> [DEBUG] Couldn't include because part of path doesn't exist. path="./web"

Typically the `codeclimate analyze` command is passed a path relative to the root of the project you'd like to analyze. Then, that code gets mounted into a container at `/code`. 

Here's an example of invoking the docker run command directly [passing the correct volumes](https://github.com/codeclimate/codeclimate#usage). 

Some things to try:

- What happens when you run `codeclimate analyze` directly from the command line, within the root directory of your project?
- What happens when you update the volumes passed into the container to match the path set up in https://github.com/codeclimate/codeclimate#usage? For instance:

```
test-server:
  build: .
  dockerfile: ./Dockerfile
  command: npm run ci
  volumes:
    - .:/web

codeclimate:
  image: codeclimate/codeclimate
  command: analyze -f html
  volumes:
    - ./:/code
    - /var/run/docker.sock:/var/run/docker.sock
    - /tmp/cc:/tmp/cc

  environment:
    - CODECLIMATE_DEBUG=1
```

Hope some of that information helps. Let me know what those commands output.
