### ISSUE TITLE
where does the output get stored?

### ISSUE THREAD

**Issue by vesper8** [codeclimate/codeclimate#616]
Sorry it seems I am missing something.

Just installed the latest version of this last night using brew.

I browse to a repository containing a laravel php project

I run codeclimate init to create the yml

I then add the phpsniffer by running this

codeclimate engines:enable phpcodesniffer

this updates a bunch of docker instances.. all good.

I then modify my codeclimate.yml file so it looks like this:

```
---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
  phpcodesniffer:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.php"
exclude_paths:
- config/
- node_modules/
- tests/
- vendor/
```

I then tried to run "codeclimate analyze -f html".. nothing happened for a while.. and then it ended and I can't find any new files. I was expecting to find some kind of report.html so I could look at the results

I then tried to run

```
CODECLIMATE_DEBUG=1 codeclimate analyze -f html
```

And I see it is doing the analyzing and it is printing out the report in .html, but still at the end of this I can't find the actual html file

Is it stored on the docker image? I looked in the repo's folder, I looked in my home folder.. can't find it

where is it? Can I specify where I want the output file to be stored?

Thanks!
