### ISSUE TITLE
Using personal stylelint modules

### ISSUE THREAD

**Issue by theorise** [codeclimate/codeclimate#663]
We have created two NPM packages we share across multiple projects, which contain our linting rules. One for eslint, one for stylelint.

The setup for eslint is working as follows:

**eslint/index.js**
```
module.exports = {
  plugins: [
    'import',
    'react',
  ],
  extends: [
    'eslint:recommended',
    'airbnb',
    'plugin:import/errors',
    'plugin:import/warnings',
    'plugin:react/recommended',
  ],
  rules: {
    'import/default': [0],
    'import/prefer-default-export': [0],
    'no-constant-condition': [0],
    'no-param-reassign': [0],
    'react/jsx-filename-extension': [0],
    'react/prefer-stateless-function': [2, { ignorePureComponents: true }],
    'react/jsx-closing-bracket-location': [0],
    'react/jsx-boolean-value': [0],
    'class-methods-use-this': [0],
    'no-class-assign': [0],
  },
};
```

**project/.eslintrc**
```
{
    "extends": "eslint-config-dbk"
}
```

**project/.codeclimate.yml**
```
---
engines:
  stylelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "src/**/*.less"
  - "src/**/*.js"
  - "src/**/*.jsx"
```

Using a similar setup for stylelint however, throws this error:
```
•• Timing: .engineConfig: 0.182s
Error: Could not find "stylelint-config-dbk". Do you need a `configBasedir`?
See our documentation at https://docs.codeclimate.com/docs/stylelint for more information.
```
The setup:

**stylelint/index.js**
```
{
    "extends": "[stylelint-config-dbk]"
}
```

**project/.stylelintrc**
```
{
    "extends": "[stylelint-config-dbk]"
}
```

Is there a way of supporting this functionality eslint is offering, or am I doing something wrong in the setup?
