### ISSUE TITLE
No engines found in valid configuration

### ISSUE THREAD

**Issue by halfpastfouram** [codeclimate/codeclimate#691]
When trying to analyze code in an automated pipeline I'm getting the error "No enabled engines.". That's weird since the configuration is present and when testing locally, the configuration is valid.

A message about no configured engines is present in both these situations:

- When validating.
- When running the analyze command:
    ```
    docker run --env CODECLIMATE_CODE="$PWD" --env CODECLIMATE_DEBUG=1 \
        --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock \
        --volume /tmp/cc:/tmp/cc codeclimate/codeclimate analyze -f json > codeclimate.json
    ```
    Returns the error message:
    > No enabled engines. Add some to your .codeclimate.yml file!

In this screenshot you can see the contents from the configuration file and the run commands:
![screenshot 2017-06-27 11 35 41](https://user-images.githubusercontent.com/3202331/27581087-e3907528-5b2c-11e7-975d-a6da435e817e.png)

I'm expecting the configuration to work since it works when I run it locally. Here is the configuration:

```
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php,phtml"
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.php"
  - "**.phtml"
exclude_paths:
- vendor/
- test/
```
## More details:
- `uname -a` returns:
    > Linux staging 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux
- `docker version` returns:
    > Client:
    > Version:      17.03.1-ce
    > API version:  1.27
    > Go version:   go1.7.5
    > Git commit:   c6d412e
    > Built:        Mon Mar 27 17:07:28 2017
    > OS/Arch:      linux/amd64
    >
    >Server:
    > Version:      17.03.1-ce
    > API version:  1.27 (minimum version 1.12)
    > Go version:   go1.7.5
    > Git commit:   c6d412e
    > Built:        Mon Mar 27 17:07:28 2017
    > OS/Arch:      linux/amd64
    > Experimental: false
    >
- `env | grep "^DOCKER_"` returns nothing.

**Comment by halfpastfouram** [comment]
I've been trying to find out what caused this but still have no clue thus far. When I use the same configuration locally everything works as expected.

# Details of my local machine:
- `uname -a` returns:
   > Darwin Bobs-MacBook-Pro.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
- `docker version` returns:
    > Client:
    > Version:      17.03.1-ce
    > API version:  1.27
    > Go version:   go1.7.5
    > Git commit:   c6d412e
    > Built:        Tue Mar 28 00:40:02 2017
    > OS/Arch:      darwin/amd64
    >
    >Server:
    > Version:      17.03.1-ce
    > API version:  1.27 (minimum version 1.12)
    > Go version:   go1.7.5
    > Git commit:   c6d412e
    > Built:        Fri Mar 24 00:00:50 2017
    > OS/Arch:      linux/amd64
    > Experimental: true

**Comment by aalimovs** [comment]
Is this on GitLab by any chance? Having exactly the same issue

**Comment by nporteschaikin** [comment]
@halfpastfouram @aalimovs 👋  Thanks for reaching out! Apologies for how long it took to reply. Were you able to remedy this?

**Comment by halfpastfouram** [comment]
@aalimovs Yes this occurs in a docker container created by gitlab-ci.

@nporteschaikin I have not found a solution for this and gave up on it. Is there anything I can do to help locate the source of the problem? I still really want it to work.

**Comment by wfleming** [comment]
>  in a docker container

This might be part of what's up.

I'm guessing that the `docker.sock` available within your container may be mounted into that container from the host running the docker daemon. Launching docker containers from within docker containers can make the file paths for mounting volumes rather confusing, since the source path needs to be the path on the host machine, not the path within the docker container at that point.

So `$PWD` within your current docker container may possibly not point to the same directory you expect it to within the `codeclimate/codeclimate` container.

This is just a quick guess based on the symptoms described here. To test out whether this might be affecting you, you can run `docker run --rm -v "$PWD:/code" --entrypoint "/bin/sh" codeclimate/codeclimate -c "cat /code/.codeclimate.yml"` within your pipeline from the same terminal you were running the other commands in your screenshot, and see if that cats out the contents you expect for your config.

**Comment by halfpastfouram** [comment]
@wfleming Thank you for your input. I've ran the command in the pipeline as you suggested:

```
docker run --rm -v "$PWD:/code" --entrypoint "/bin/sh" codeclimate/codeclimate \
    -c "cat /code/.codeclimate.yml"
---
engines: {}
ratings:
  paths: []
exclude_paths: []
```

**Comment by wfleming** [comment]
@halfpastfouram I think that confirms my suspicion that `$PWD` is a different directory within the docker container you're in & on the host running the docker daemon, since that doesn't at all match the contents of your config you've shown elsewhere. How & why there's a `.codeclimate.yml` in that other directory I really don't know.

Would you be able to share more of your `.gitlablab-ci.yml`? I'm assuming you set this up based on [GitLab's docs](https://docs.gitlab.com/ee/ci/examples/code_climate.html), since your command looks similar to their docs.

You also could try and get more details by running other commands similar to what I suggested to do the `cat`: e.g. you could use the same basic formulation to do an `ls -al /code` and see if the rest of that directory does look like your project's root or something else.

You also might want to consider contacting GitLab support about this if you haven't already: what you've shown me makes me think the problem is arrising from confusion about paths within docker containers on GitLab's CI system, so they might be able to point you in the right direction better than we will.

**Comment by grauwoelfchen** [comment]
Hi there,

I also got exactly same issue. but it's solved. I would like to report my situation and (mis-) understanding here. It seems that this problem comes from usage of  `dind` (docker in docker) service.

##### 1. `--privileged` option

If you run `gitlab-ci-multi-runner` on your machine, it might be also needed to add `--docker-privileged` option to `gitlab-ci-multi-runner`.

This is option is mentioned in here (Use Docker in Docker Executor Section):
https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-in-docker-executor

I've found also these reports which are caused by the lack of this option use:
https://gitlab.com/gitlab-org/gitlab-runner/issues/1544
https://gitlab.com/gitlab-org/gitlab-runner/issues/2255

##### 2. `overlay`

If you use `DOCKER_DRIVER` as `overlay` or `overlay2` (like sample in this [gitlab document](https://docs.gitlab.com/ee/ci/examples/code_climate.html)), docker must have overlay fs support, otherwise volume (`/code`) will be empty with this environment variable at runtime. (In my case, the lack of this driver was problem, I fogot to run `modprobe overlay`...)

It needs kernel option `CONFIG_OVERLAY_FS`. I use Gentoo Linux, and ebuild of docker has `overlay` use flag.

```zsh
% equery u app-emulation/docker
...
 + + overlay        : Enables dependencies for the "overlay" graph driver, including necessary kernel flags. 
...
```

About overlay fs driver, see this section:
https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#using-the-overlayfs-driver

Also its caching is keep being discussed at here:
https://gitlab.com/gitlab-org/gitlab-ce/issues/17861

This is my runner script and a stage configuration of `.gitlab-ci.yml`.

```zsh
% path/to/bin/gitlab-ci-multi-runner exec docker \
--cache-dir /cache \
--docker-privileged \
--docker-volumes /path/to/tmp/cache:/cache \
--docker-volumes /var/run/docker.sock:/var/run/docker.sock
```

```yaml
codequality:
  stage: codequality
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  before_script:
    - docker pull codeclimate/codeclimate
    - docker run --env CODECLIMATE_CODE="$PWD"
      --volume "$PWD":/code
      --volume /var/run/docker.sock:/var/run/docker.sock
      --volume /tmp/cc:/tmp/cc
      codeclimate/codeclimate validate-config
    - docker run --env CODECLIMATE_CODE="$PWD"
      --volume "$PWD":/code
      --volume /var/run/docker.sock:/var/run/docker.sock
      --volume /tmp/cc:/tmp/cc
      codeclimate/codeclimate engines:install
  script:
    - docker run --env CODECLIMATE_CODE="$PWD"
      --volume "$PWD":/code
      --volume /var/run/docker.sock:/var/run/docker.sock
      --volume /tmp/cc:/tmp/cc
      codeclimate/codeclimate analyze -f json > codequality.json
  artifacts:
    paths:
      - codequality.json
```

It will pull images every time, but it works on both `gitlab.com` and my desktop.

I don't know why the setup above gitlab document uses `codeclimate init` in CI.
If you have only an empty `.codeclimate.yml` in `/code` directory, it might be caused by it.
\# @wfleming 's suggestion `ls -al /code` was very usefull to me to the understanding.

Anyway, apparently, I think, it seems that it's not issue at codeclimate side.  
Thank you for great tool :-)
