### ISSUE TITLE
Support for the new codeclimate config file

### ISSUE THREAD

**Issue by daften** [codeclimate/codeclimate#763]
According to https://docs.codeclimate.com/docs/advanced-configuration there's a new codeclimate.yml configuration file format.

When I try the one below in package https://github.com/digipolisgent/robo-digipolis-general, I get 

```
blommedi at macbook-pro in ~/Workspaces/infrastructuur/robo/robo-digipolis-general on develop [!]
$ codeclimate analyze
No enabled engines. Add some to your .codeclimate.yml file!
```

```
version: "2"
plugins:
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2"
  phpmd:
    enabled: true
    config:
      CleanCode/StaticAccess:
        enabled: false
      Naming/ShortVariable:
        enabled: false
      Naming/ShortMethodName:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
        - php:
  fixme:
    enabled: true
  markdownlint:
    enabled: true
    config:
      MD024:
        enabled: false
exclude_patterns:
  - "**/vendor/**/*"
  - "**/.idea/**/*"
  - "tests/"
```
