### ISSUE TITLE
Document include_paths

### ISSUE THREAD

**Issue by benmccann** [codeclimate/codeclimate#803]
According to https://github.com/codeclimate/codeclimate/pull/298 there is an option called `include_paths`. However, this option does not seem to be documented. A good place to mention it might be https://docs.codeclimate.com/v1.0/docs/excluding-files-and-folders

As an example of what I'm trying to do, I'd like to run only a single check (the `eslint-4` engine) on the `test/` and `samples/` directories and not run the other engines. Is the config below a valid way of doing that?
```
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-4"
    include_paths:
    - 'test/'
    - 'samples/'
  fixme:
    enabled: true
ratings:
  paths:
  - "src/**/*.js"
exclude_paths:
- '.github/'
- 'dist/'
- 'test/'
- 'docs/'
- 'samples/'
- 'scripts/'
- '**.md'
- '**.json'
- 'gulpfile.js'
- 'karma.conf.js'
```
