### ISSUE TITLE
Engine attempting to access excluded files

### ISSUE THREAD

**Issue by elwayman02** [codeclimate/codeclimate#82]
I'm on codeclimate 0.2.8 running the following config:

```
---
engines:
  eslint:
    enabled: true
  csslint:
    enabled: false
  fixme:
    enabled: true
  watson:
    enabled: true
ratings:
  paths:
  - "app/**"
exclude_paths:
- bower_components/**/*
- dist/**/*
- node_modules/**/*
- tests/**/*
- tmp/**/*
- vendor/**/*
```

I get the following error for `codeclimate analyze`:

```
Starting analysis
Running eslint: Done!
error: (CC::Analyzer::Engine::EngineFailure) engine eslint failed with status 1 and stderr
/usr/src/app/node_modules/glob/sync.js:321
        throw er
              ^
Error: EACCES, permission denied '/code/tmp/asset_rewrite-cache_path-RFcmONBd.tmp'
    at Error (native)
    at Object.fs.readdirSync (fs.js:761:18)
    at GlobSync._readdir (/usr/src/app/node_modules/glob/sync.js:275:41)
    at GlobSync._readdirInGlobStar (/usr/src/app/node_modules/glob/sync.js:254:20)
    at GlobSync._readdir (/usr/src/app/node_modules/glob/sync.js:263:17)
    at GlobSync._processGlobStar (/usr/src/app/node_modules/glob/sync.js:330:22)
    at GlobSync._process (/usr/src/app/node_modules/glob/sync.js:128:10)
    at GlobSync._processGlobStar (/usr/src/app/node_modules/glob/sync.js:363:10)
    at GlobSync._process (/usr/src/app/node_modules/glob/sync.js:128:10)
    at GlobSync._processGlobStar (/usr/src/app/node_modules/glob/sync.js:363:10)
```

The project is an Ember 1.12 app w/ over 32,000 lines of code across 200+ files.

I thought the issue was related to https://github.com/codeclimate/codeclimate-eslint/issues/1, but even disabling eslint surfaces the same error for the fixme engine instead.  Seems to be something with the CLI itself, then.
