### ISSUE TITLE
check exclude_patterns: must be a hash

### ISSUE THREAD

**Issue by schnubor** [codeclimate/codeclimate#854]
Hi there!

I'm having trouble validating my `.codeclimate.yml`, specifically the `exclude_patterns`:

```
version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 25
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      threshold: 45 # language-specific defaults. an override will affect all languages.
  exclude_patterns:
    - "node_modules/"
    - "scripts/"
    - "dist/"
    - "dll/"
    - "src/dll/"
    - "src/app/assets/"
    - "src/app/styles/"
    - "src/app/utils/"
    - "**/*.log"
    - "**/*.json"
```

I'm running `codeclimate validate-config` and get `ERROR: check exclude_patterns: must be a hash`  

I get the same error when using the config found on the website: https://docs.codeclimate.com/docs/advanced-configuration#section-exclude-patterns

`codeclimate version` is `0.75.0`

Any hints on this?

Cheers,
Christian
