### ISSUE TITLE
Alternative to exclude_fingerprints?

### ISSUE THREAD

**Issue by tillig** [codeclimate/codeclimate#888]
I am currently able to exclude some false positives in the `duplication` plugin/engine using `exclude_fingerprints` like this:

```yaml
---
version: "2"
checks:
  argument-count:
    config:
      threshold: 6
  file-lines:
    enabled: false
  method-lines:
    config:
      threshold: 100
  return-statements:
    enabled: false
plugins:
  duplication:
    exclude_fingerprints:
    - "876e809d86a7ba31b169ff0ccd05a2a5"
    - "281b544dfb713a0120ebba8cf7a82770"
    - "2425b8596dcd296f319e31a788af5993"
    - "658fe21f6fc5f431c8f154323fb7c521"
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - HACK
exclude_patterns:
- "artifacts/"
- "build/"
- "test/"
- "**/bin/"
- "**/obj/"
```

However, upon validating the configuration it tells me that `exclude_fingerprints` is deprecated. [I can find the code](https://github.com/codeclimate/codeclimate/blob/e2f7d7f7f75c0279351ddeab1f99fd50e335406b/lib/cc/config/validation/engine_validator.rb#L90) where the warning is issued. I can see that `exclude_paths` has been replaced with `exclude_patterns`... but what is the replacement for `exclude_fingerprints` if it's deprecated? I couldn't find that in the documentation and the [Duplication engine docs don't cover it, either](https://docs.codeclimate.com/docs/duplication).
