### ISSUE TITLE
"Exlude all glob" for dotfiles

### ISSUE THREAD

**Issue by MDSLKTR** [codeclimate/codeclimate#891]
Hey there,

I have an issue with excluding dotfiles in my project root. I use the exclude pattern "**/*" to get rid of all files in the project root. This however doesn't work for project config files like .editorconfig or .php_cs.dist. I tried a few globs like "**/.*" without success. Usually the editorconfig plugin will cause a hangup if the glob is not valid. Is there a recommended way to get rid of these files for checking?

Regards,
Simon

**Comment by filipesperandio** [comment]
Hey,

I've tried the below and it successfully excluded dotfiles.
```yml
exclude_paths:
  - "**/.*"
```

You may try `CODECLIMATE_DEBUG=1 codeclimatea analyze` to get extra output about what is going on if the above isn't enough.

An alternative way is exclude everything and _unexclude_ the files you want.
```yml
exclude_paths:
  - "**/.*"
  - "**/*"
  - "!**/*.php"
```

**Comment by MDSLKTR** [comment]
Hey @filipesperandio,
thanks for the quick reply. The above seems like the right call but unfortunately adding `**/.*` causes the editorconfig plugin to hangup in our current check chain. This also happens when i run it locally `CODECLIMATE_DEBUG=1 codeclimate analyze -e editorconfig`

```

exclude_patterns:
  - "**/*"
  - "**/.*"
  - ".circleci/"
  - ".vagrant/"
  - "ansible/"
  - "deployment/"
  - "node_modules/"
  - "www/"
  - "Vagrantfile"
```

This is the output locally: https://gist.github.com/MDSLKTR/3fd6dad1f3ea8eb4d72bd39c14968b2d

Remote it will just timeout without any logs

**Comment by filipesperandio** [comment]
Have you tried unexcluding the specific files in the plugin and excluding everything else?
Working with the exclude patterns can be challenging sometimes.

```yml
 editorconfig:
    enabled: true
    exclude_patterns:
      - "**/*"
      - "**/.*"
      - "!www/custom/plugins/PxswTheme/Resources/Themes/Frontend/PxswTheme/frontend/_public/src/js/**"
      - "!www/custom/plugins/PxswTheme/Resources/Themes/Frontend/PxswTheme/frontend/_public/src/scss/**"
      - "!.editorconfig"
```
