### ISSUE TITLE
Sonar php doesn't exclude path from checking

### ISSUE THREAD

**Issue by grozwalker** [codeclimate/codeclimate#925]
I want to exclude database folder from checking by sonar-php, but it doesn't work

```
version: "2"
plugins:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      ignore_warnings: true
      standard: "./phpcs.xml"
  sonar-php:
    enabled: true
    tests:
      - tests/**
  phpmd:
    enabled: true
    config:
      file_extensions:
        - php
    checks:
      CleanCode/StaticAccess:
        enabled: false
exclude_patterns:
- "database/"
- "tests/"
- "spec/"
- "**/vendor/"
```

But have error in
```
Found in database/migrations/2019_09_04_211829_create_read_chapters_table.php by sonar-php
```

What am I doing wrong?

P.s. all exclude patterns doesn't work
